//
//
#include <jni.h>
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef MEIGESERIALPORT_SERIALPORTOPTIONS_H
#define MEIGESERIALPORT_SERIALPORTOPTIONS_H
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL
Java_com_meidical_meigeserialport_SerialPort_open
        (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);


JNIEXPORT jint JNICALL
Java_com_meidical_meigeserialport_SerialPort_select
        (JNIEnv *, jobject, jlong);


JNIEXPORT jobject JNICALL
Java_com_meidical_meigeserialport_SerialPort_descriptor
        (JNIEnv *, jobject, jlong);


JNIEXPORT void JNICALL
Java_com_meidical_meigeserialport_SerialPort_close
        (JNIEnv *, jobject, jlong);


JNIEXPORT void JNICALL
Java_com_meidical_meigeserialport_SerialPort_writeFile
        (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
